### ISSUE TITLE
question about yrl api

### ISSUE THREAD

**Issue by mixartemev** [Dolfik1/yarealty#1]
https://github.com/Dolfik1/yarealty/blob/24ff611e6243955e75f15a5e45186375dede02ee/crawler.py#L8
Please, could you prompt where/how can I get all possible values for '_format' and 'pageType' parameters?

**Comment by Dolfik1** [comment]
There's no public documentation for Yandex Realty API. You can apply reverse engineering to find it out. https://realty.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/

Also you can try analyze android app: https://play.google.com/store/apps/details?id=com.yandex.mobile.realty
